routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

Route::group(['middleware' => ['auth', 'approved']], function () {
    Route::get('books/{book_id}/chapters.json', function($book_id)
    {
        return App\BookChapter::where('book_id', $book_id)->select('id','chapter_title')->get();
    });
    Route::get('/home', 'HomeController@index');
    Route::get('/ndihma','HomeController@ndihma');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::get('books/shelf', ['uses' => 'BooksController@shelf', 'as' => 'books.shelf']);
    Route::get('books/shelf/{book}', ['uses' => 'BooksController@book', 'as' => 'books.book']);
    Route::get('books/redeem', ['uses' => 'BooksController@redeem', 'as' => 'books.redeem']);
    Route::get('tests/take/{id}', ['uses' => 'TestsController@take', 'as' => 'tests.take']);
    Route::get('test_results/{user_id}/test/{id}', ['uses' => 'TestResultsController@view', 'as' => 'testsresult.view']);
    Route::post('tests/taking/{id}', ['uses' => 'TestResultsController@taking', 'as' => 'testsresult.take']);
    Route::resource('books', 'BooksController');
    Route::post('books_mass_destroy', ['uses' => 'BooksController@massDestroy', 'as' => 'books.mass_destroy']);
    Route::resource('book_codes', 'BookCodesController');
    Route::post('book_codes_mass_destroy', ['uses' => 'BookCodesController@massDestroy', 'as' => 'book_codes.mass_destroy']);
    Route::resource('tests', 'TestsController');
    Route::post('tests_mass_destroy', ['uses' => 'TestsController@massDestroy', 'as' => 'tests.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('answers', 'AnswersController');
    Route::post('answers_mass_destroy', ['uses' => 'AnswersController@massDestroy', 'as' => 'answers.mass_destroy']);
    Route::resource('videos', 'VideosController');
    Route::post('videos_mass_destroy', ['uses' => 'VideosController@massDestroy', 'as' => 'videos.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('districts', 'DistrictsController');
    Route::post('districts_mass_destroy', ['uses' => 'DistrictsController@massDestroy', 'as' => 'districts.mass_destroy']);
    Route::resource('schools', 'SchoolsController');
    Route::post('schools_mass_destroy', ['uses' => 'SchoolsController@massDestroy', 'as' => 'schools.mass_destroy']);
    Route::get('book_chapters/chapter/{id}', 'BookChaptersController@chapter');
    Route::resource('book_chapters', 'BookChaptersController');
    Route::post('book_chapters_mass_destroy', ['uses' => 'BookChaptersController@massDestroy', 'as' => 'book_chapters.mass_destroy']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'MessengerController');
});

app/Book.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Book
 *
 * @package App
 * @property string $name
 * @property string $cover
 * @property text $description
 * @property string $type
*/
class Book extends Model
{
    protected $fillable = ['name', 'cover', 'description', 'type'];
    
    public static function boot()
    {
        parent::boot();

        Book::observe(new \App\Observers\UserActionsObserver);
    }
    
    public function teachers()
    {
        return $this->belongsToMany(User::class, 'book_user');
    }
    
    public function students()
    {
        return $this->belongsToMany(User::class, 'book_student');
    }
    public function bookcodes()
    {
        return $this->hasMany(BookCode::class, 'book_codes');
    }
     
}

app/Http/Controllers/Api/V1/BooksController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Book;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreBooksRequest;
use App\Http\Requests\UpdateBooksRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class BooksController extends Controller
{
    use FileUploadTrait;

    public function index()
    {
        return Book::all();
    }

    public function show($id)
    {
        return Book::findOrFail($id);
    }

    public function update(UpdateBooksRequest $request, $id)
    {
        $request = $this->saveFiles($request);
        $book = Book::findOrFail($id);
        $book->update($request->all());

        return $book;
    }

    public function store(StoreBooksRequest $request)
    {
        $request = $this->saveFiles($request);
        $book = Book::create($request->all());

        return $book;
    }

    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $book->delete();
        return '';
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\StoreBooksRequest;
use App\Http\Requests\UpdateBooksRequest;
use App\Http\Controllers\Traits\FileUploadTrait;
use Yajra\Datatables\Datatables;

class BooksController extends Controller
{
    use FileUploadTrait;

    /**
     * Display a listing of Book.
     *
     * @return \Illuminate\Http\Response
     */
    public function shelf()
    {
        if (! Gate::allows('book_shelf')) {
            return abort(401);
        }
        $books = Auth::user()->books()->get()->chunk(6);
 

        return view('books.shelf', compact('books'));
    }

    public function redeem()
    {
        if (! Gate::allows('book_access')) {
            return abort(401);
        }
        $books = Auth::user()->books()->get()->chunk(6);
 

        return view('books.shelf', compact('books'));
    }

    /**
     * Display a listing of Book.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('book_access')) {
            return abort(401);
        }
        $books = Book::all();

        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating new Book.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('book_create')) {
            return abort(401);
        }
        $relations = [
            'teachers' => \App\User::get()->pluck('name', 'id'),
        ];

        return view('books.create', $relations);
    }

    /**
     * Store a newly created Book in storage.
     *
     * @param  \App\Http\Requests\StoreBooksRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBooksRequest $request)
    {
        if (! Gate::allows('book_create')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $book = Book::create($request->all());
        $book->teachers()->sync(array_filter((array)$request->input('teachers')));

        return redirect()->route('books.index');
    }


    /**
     * Show the form for editing Book.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('book_edit')) {
            return abort(401);
        }
        $relations = [
            'teachers' => \App\User::get()->pluck('name', 'id'),
        ];

        $book = Book::findOrFail($id);

        return view('books.edit', compact('book') + $relations);
    }

    /**
     * Update Book in storage.
     *
     * @param  \App\Http\Requests\UpdateBooksRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBooksRequest $request, $id)
    {
        if (! Gate::allows('book_edit')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $book = Book::findOrFail($id);
        $book->update($request->all());
        $book->teachers()->sync(array_filter((array)$request->input('teachers')));

        return redirect()->route('books.index');
    }


    /**
     * Display Book.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('book_view')) {
            return abort(401);
        }
        $relations = [
            'teachers' => \App\User::get()->pluck('name', 'id'),
            'book_codes' => \App\BookCode::where('book_id', $id)->get(),
            'videos' => \App\Video::where('chapter_id', $id)->get(),
            'book_chapters' => \App\BookChapter::where('book_id', $id)->get(),
            'tests' => \App\Test::where('book_id', $id)->get(),
        ];

        $book = Book::findOrFail($id);

        return view('books.show', compact('book') + $relations);
    }



    /**
     * Display Book.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function book($id)
    {
        if (! Gate::allows('book_view')) {
            return abort(401);
        }
        $relations = [
            'teachers' => \App\User::get()->pluck('name', 'id'),
            'book_codes' => \App\BookCode::where('book_id', $id)->get(),
            'videos' => \App\Video::where('chapter_id', $id)->get(),
            'book_chapters' => \App\BookChapter::where('book_id', $id)->get(),
            'tests' => \App\Test::where('book_id', $id)->get(),
        ];

        $book = Book::findOrFail($id);

        return view('books.book', compact('book') + $relations);
    }


    /**
     * Remove Book from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('book_delete')) {
            return abort(401);
        }
        $book = Book::findOrFail($id);
        $book->delete();

        return redirect()->route('books.index');
    }

    /**
     * Delete all selected Book at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('book_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Book::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/books/book.blade.php
@extends('layouts.app')
@section('content')
 <div class="row book">
    <div class="col-md-3">  <h1>{{ $book->name }}</h1>@if($book->cover)<a href="{{ asset('uploads/' . $book->cover) }}" target="_blank"><img width="100%" src="{{ asset('uploads/' . $book->cover) }}"/></a>@endif <br> {!!$book->description!!} </div>
    <div class="col-md-3">
      <h1> Njesitë</h1>
        @if (count($book_chapters) > 0)
        @foreach ($book_chapters as $book_chapter)
        <div class="media" data-entry-id="{{ $book_chapter->id }}">
           
            <div class="media-body">
               
              <a  href="/book_chapters/chapter/{{ $book_chapter->id }}?file=/uploads/{{ $book_chapter->chapter_file }}" class="btn btn-primary btn-lg test-buttons "  >
                 <h4 class="media-heading">{{ $book_chapter->chapter_title }}</h4>
                </a>
            </div>
        </div>
        @endforeach
        @else
        <div>
            <div colspan="7">@lang('quickadmin.qa_no_entries_in_table')</div>
        </div>
        @endif
    </div>
    <div class="col-md-3">  
    <h1>Testet</h1>

    @if (count($tests) > 0)
        @foreach ($tests as $test)


        <div class="media"  data-entry-id="{{ $test->id }}">
               @php $TestResult = \App\TestResult::where([['test_id','=',$test->id],['user_id','=', Auth::user()->id]])->first();  
                 @endphp
                @if($TestResult == null)
                @can('test_view')
                <a href="/tests/take/{{$test->id}}" class="btn test-buttons  btn-xs btn-primary"> <h4 class="media-heading">{{ $test->name }}</h4></a>
                @endcan
                @else 
                   <a href="#" class="btn test-buttons  btn-xs btn-primary"><h4 class="media-heading"> Keni bere testin tashme.</h4></a>
                @endif
           
        </div>
        @endforeach
        @else
        <div>
            <div colspan="8">@lang('quickadmin.qa_no_entries_in_table')</div>
        </div>
    @endif</div>
   
</div> 

</div>
            @stop

resources/views/books/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.books.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['books.store'], 'files' => true,]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('cover', 'Cover', ['class' => 'control-label']) !!}
                    {!! Form::file('cover', ['class' => 'form-control', 'style' => 'margin-top: 4px;']) !!}
                    {!! Form::hidden('cover_max_size', 8) !!}
                    {!! Form::hidden('cover_max_width', 4000) !!}
                    {!! Form::hidden('cover_max_height', 4000) !!}
                    <p class="help-block"></p>
                    @if($errors->has('cover'))
                        <p class="help-block">
                            {{ $errors->first('cover') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('description', 'Description', ['class' => 'control-label']) !!}
                    {!! Form::textarea('description', old('description'), ['class' => 'form-control ', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('description'))
                        <p class="help-block">
                            {{ $errors->first('description') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('type', 'Type', ['class' => 'control-label']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('type'))
                        <p class="help-block">
                            {{ $errors->first('type') }}
                        </p>
                    @endif
                    <div>
                        <label>
                            {!! Form::radio('type', 'book', false) !!}
                            Liber 
                        </label>
                    </div>
                    <div>
                        <label>
                            {!! Form::radio('type', 'workbook', false) !!}
                            Fletore pune
                        </label>
                    </div>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('teachers', 'Teachers', ['class' => 'control-label']) !!}
                    {!! Form::select('teachers[]', $teachers, old('teachers'), ['class' => 'form-control select2', 'multiple' => 'multiple']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('teachers'))
                        <p class="help-block">
                            {{ $errors->first('teachers') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/books/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.books.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.books.fields.name')</th>
                            <td>{{ $book->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.books.fields.cover')</th>
                            <td>@if($book->cover)<a href="{{ asset('uploads/' . $book->cover) }}" target="_blank"><img src="{{ asset('uploads/thumb/' . $book->cover) }}"/></a>@endif</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.books.fields.description')</th>
                            <td>{!! $book->description !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.books.fields.type')</th>
                            <td>{{ $book->type }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.books.fields.teachers')</th>
                            <td>
                                @foreach ($book->teachers as $singleTeachers)
                                    <span class="label label-info label-many">{{ $singleTeachers->name }}</span>
                                @endforeach
                            </td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#bookcodes" aria-controls="bookcodes" role="tab" data-toggle="tab">Book codes</a></li>
<li role="presentation" class=""><a href="#video" aria-controls="video" role="tab" data-toggle="tab">Video </a></li>
<li role="presentation" class=""><a href="#bookchapters" aria-controls="bookchapters" role="tab" data-toggle="tab">Book chapters</a></li>
<li role="presentation" class=""><a href="#test" aria-controls="test" role="tab" data-toggle="tab">Test</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="bookcodes">
<table class="table table-bordered table-striped {{ count($book_codes) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.book-codes.fields.book')</th>
                        <th>@lang('quickadmin.book-codes.fields.code')</th>
                        <th>&nbsp;</th>
        </tr>
    </thead>

    <tbody>
        @if (count($book_codes) > 0)
            @foreach ($book_codes as $book_code)
                <tr data-entry-id="{{ $book_code->id }}">
                    <td>{{ $book_code->book->name or '' }}</td>
                                <td>{{ $book_code->code }}</td>
                                <td>
                                    @can('book_code_view')
                                    <a href="{{ route('book_codes.show',[$book_code->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('book_code_edit')
                                    <a href="{{ route('book_codes.edit',[$book_code->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('book_code_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['book_codes.destroy', $book_code->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="6">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="video">
<table class="table table-bordered table-striped {{ count($videos) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.video.fields.book')</th>
                        <th>@lang('quickadmin.video.fields.name')</th>
                        <th>@lang('quickadmin.video.fields.embed-code')</th>
                        <th>@lang('quickadmin.video.fields.video-file')</th>
                        <th>@lang('quickadmin.video.fields.video-thumbnail')</th>
                        <th>&nbsp;</th>
        </tr>
    </thead>

    <tbody>
        @if (count($videos) > 0)
            @foreach ($videos as $video)
                <tr data-entry-id="{{ $video->id }}">
                    <td>{{ $video->book->name or '' }}</td>
                                <td>{{ $video->name }}</td>
                                <td>{!! $video->embed_code !!}</td>
                                <td>@if($video->video_file)<a href="{{ asset('uploads/' . $video->video_file) }}" target="_blank">Download file</a>@endif</td>
                                <td>@if($video->video_thumbnail)<a href="{{ asset('uploads/' . $video->video_thumbnail) }}" target="_blank"><img src="{{ asset('uploads/thumb/' . $video->video_thumbnail) }}"/></a>@endif</td>
                                <td>
                                    @can('video_view')
                                    <a href="{{ route('videos.show',[$video->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('video_edit')
                                    <a href="{{ route('videos.edit',[$video->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('video_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['videos.destroy', $video->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="9">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="bookchapters">
<table class="table table-bordered table-striped {{ count($book_chapters) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.book-chapters.fields.chapter-title')</th>
                        <th>@lang('quickadmin.book-chapters.fields.chapter-file')</th>
                        <th>@lang('quickadmin.book-chapters.fields.book')</th>
                        <th>@lang('quickadmin.books.fields.cover')</th>
                        <th>&nbsp;</th>
        </tr>
    </thead>

    <tbody>
        @if (count($book_chapters) > 0)
            @foreach ($book_chapters as $book_chapter)
                <tr data-entry-id="{{ $book_chapter->id }}">
                    <td>{{ $book_chapter->chapter_title }}</td>
                                <td>@if($book_chapter->chapter_file)<a href="{{ asset('uploads/' . $book_chapter->chapter_file) }}" target="_blank">Download file</a>@endif</td>
                                <td>{{ $book_chapter->book->name or '' }}</td>
<td>@if($book_chapter->book && $book_chapter->book->cover)<a href="{{ asset('uploads/' . $book_chapter->book->cover) }}" target="_blank"><img src="{{ asset('uploads/thumb/' . $book_chapter->book->cover) }}"/></a>@endif</td>
                                <td>
                                    @can('book_chapter_view')
                                    <a href="{{ route('book_chapters.show',[$book_chapter->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('book_chapter_edit')
                                    <a href="{{ route('book_chapters.edit',[$book_chapter->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('book_chapter_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['book_chapters.destroy', $book_chapter->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="7">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="test">
<table class="table table-bordered table-striped {{ count($tests) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.test.fields.name')</th>
                        <th>@lang('quickadmin.test.fields.description')</th>
                        <th>@lang('quickadmin.test.fields.chapter')</th>
                        <th>@lang('quickadmin.test.fields.book')</th>
                        <th>&nbsp;</th>
        </tr>
    </thead>

    <tbody>
        @if (count($tests) > 0)
            @foreach ($tests as $test)
                <tr data-entry-id="{{ $test->id }}">
                    <td>{{ $test->name }}</td>
                                <td>{!! $test->description !!}</td>
                                <td>{{ $test->chapter->chapter_title or '' }}</td>
                                <td>{{ $test->book->name or '' }}</td>
                                <td>
                                    @can('test_view')
                                    <a href="{{ route('tests.show',[$test->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('test_edit')
                                    <a href="{{ route('tests.edit',[$test->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('test_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['tests.destroy', $test->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="8">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('books.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop