routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

Route::group(['middleware' => ['auth', 'approved']], function () {
    Route::get('books/{book_id}/chapters.json', function($book_id)
    {
        return App\BookChapter::where('book_id', $book_id)->select('id','chapter_title')->get();
    });
    Route::get('/home', 'HomeController@index');
    Route::get('/ndihma','HomeController@ndihma');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::get('books/shelf', ['uses' => 'BooksController@shelf', 'as' => 'books.shelf']);
    Route::get('books/shelf/{book}', ['uses' => 'BooksController@book', 'as' => 'books.book']);
    Route::get('books/redeem', ['uses' => 'BooksController@redeem', 'as' => 'books.redeem']);
    Route::get('tests/take/{id}', ['uses' => 'TestsController@take', 'as' => 'tests.take']);
    Route::get('test_results/{user_id}/test/{id}', ['uses' => 'TestResultsController@view', 'as' => 'testsresult.view']);
    Route::post('tests/taking/{id}', ['uses' => 'TestResultsController@taking', 'as' => 'testsresult.take']);
    Route::resource('books', 'BooksController');
    Route::post('books_mass_destroy', ['uses' => 'BooksController@massDestroy', 'as' => 'books.mass_destroy']);
    Route::resource('book_codes', 'BookCodesController');
    Route::post('book_codes_mass_destroy', ['uses' => 'BookCodesController@massDestroy', 'as' => 'book_codes.mass_destroy']);
    Route::resource('tests', 'TestsController');
    Route::post('tests_mass_destroy', ['uses' => 'TestsController@massDestroy', 'as' => 'tests.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('answers', 'AnswersController');
    Route::post('answers_mass_destroy', ['uses' => 'AnswersController@massDestroy', 'as' => 'answers.mass_destroy']);
    Route::resource('videos', 'VideosController');
    Route::post('videos_mass_destroy', ['uses' => 'VideosController@massDestroy', 'as' => 'videos.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('districts', 'DistrictsController');
    Route::post('districts_mass_destroy', ['uses' => 'DistrictsController@massDestroy', 'as' => 'districts.mass_destroy']);
    Route::resource('schools', 'SchoolsController');
    Route::post('schools_mass_destroy', ['uses' => 'SchoolsController@massDestroy', 'as' => 'schools.mass_destroy']);
    Route::get('book_chapters/chapter/{id}', 'BookChaptersController@chapter');
    Route::resource('book_chapters', 'BookChaptersController');
    Route::post('book_chapters_mass_destroy', ['uses' => 'BookChaptersController@massDestroy', 'as' => 'book_chapters.mass_destroy']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'MessengerController');
});

app/Question.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Question
 *
 * @package App
 * @property string $test
 * @property string $question
*/
class Question extends Model
{
    use SoftDeletes;

    protected $fillable = ['question', 'test_id','points'];
    
    public static function boot()
    {
        parent::boot();

        Question::observe(new \App\Observers\UserActionsObserver);
    }

    /**
     * Set to null if empty
     * @param $input
     */
    public function setTestIdAttribute($input)
    {
        $this->attributes['test_id'] = $input ? $input : null;
    }
    
    public function test()
    {
        return $this->belongsTo(Test::class, 'test_id')->withTrashed();
    }
    public function answers()
    {
        return $this->hasMany(Answer::class, 'question_id');
    }
    
}

app/Http/Controllers/Api/V1/QuestionsController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreQuestionsRequest;
use App\Http\Requests\UpdateQuestionsRequest;

class QuestionsController extends Controller
{
    public function index()
    {
        return Question::all();
    }

    public function show($id)
    {
        return Question::findOrFail($id);
    }

    public function update(UpdateQuestionsRequest $request, $id)
    {
        $question = Question::findOrFail($id);
        $question->update($request->all());

        return $question;
    }

    public function store(StoreQuestionsRequest $request)
    {
        $question = Question::create($request->all());

        return $question;
    }

    public function destroy($id)
    {
        $question = Question::findOrFail($id);
        $question->delete();
        return '';
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\StoreQuestionsRequest;
use App\Http\Requests\UpdateQuestionsRequest;

class QuestionsController extends Controller
{
    /**
     * Display a listing of Question.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('question_access')) {
            return abort(401);
        }
        $questions = Question::all();

        return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating new Question.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('question_create')) {
            return abort(401);
        }
        $relations = [
            'tests' => \App\Test::get()->pluck('name', 'id')->prepend('Please select', ''),
        ];

        return view('questions.create', $relations);
    }

    /**
     * Store a newly created Question in storage.
     *
     * @param  \App\Http\Requests\StoreQuestionsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreQuestionsRequest $request)
    {
        if (! Gate::allows('question_create')) {
            return abort(401);
        }
        $question = Question::create($request->all());

        return redirect()->route('questions.index');
    }


    /**
     * Show the form for editing Question.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('question_edit')) {
            return abort(401);
        }
        $relations = [
            'tests' => \App\Test::get()->pluck('name', 'id')->prepend('Please select', ''),
        ];

        $question = Question::findOrFail($id);

        return view('questions.edit', compact('question') + $relations);
    }

    /**
     * Update Question in storage.
     *
     * @param  \App\Http\Requests\UpdateQuestionsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionsRequest $request, $id)
    {
        if (! Gate::allows('question_edit')) {
            return abort(401);
        }
        $question = Question::findOrFail($id);
        $question->update($request->all());

        return redirect()->route('questions.index');
    }


    /**
     * Display Question.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('question_view')) {
            return abort(401);
        }
        $relations = [
            'tests' => \App\Test::get()->pluck('name', 'id')->prepend('Please select', ''),
            'answers' => \App\Answer::where('question_id', $id)->get(),
        ];

        $question = Question::findOrFail($id);

        return view('questions.show', compact('question') + $relations);
    }


    /**
     * Remove Question from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('question_delete')) {
            return abort(401);
        }
        $question = Question::findOrFail($id);
        $question->delete();

        return redirect()->route('questions.index');
    }

    /**
     * Delete all selected Question at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('question_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Question::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questions.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['questions.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('test_id', 'Test', ['class' => 'control-label']) !!}
                    {!! Form::select('test_id', $tests, old('test_id'), ['class' => 'form-control select2']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('test_id'))
                        <p class="help-block">
                            {{ $errors->first('test_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', 'Pyetja *', ['class' => 'control-label']) !!}
                    {!! Form::text('question', old('question'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('points', 'Piket*', ['class' => 'control-label']) !!}
                    {!! Form::text('points', old('points'), ['class' => 'form-control', 'placeholder' => 'Piket']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('points'))
                        <p class="help-block">
                            {{ $errors->first('points') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questions.title')</h3>
    
    {!! Form::model($question, ['method' => 'PUT', 'route' => ['questions.update', $question->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('test_id', 'Test', ['class' => 'control-label']) !!}
                    {!! Form::select('test_id', $tests, old('test_id'), ['class' => 'form-control select2']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('test_id'))
                        <p class="help-block">
                            {{ $errors->first('test_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', 'Question*', ['class' => 'control-label']) !!}
                    {!! Form::text('question', old('question'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
               <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('points', 'Piket*', ['class' => 'control-label']) !!}
                    {!! Form::text('points', old('points'), ['class' => 'form-control', 'placeholder' => 'Piket']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('points'))
                        <p class="help-block">
                            {{ $errors->first('points') }}
                        </p>
                    @endif
                </div>
            </div>   
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questions.title')</h3>
    @can('question_create')
    <p>
        <a href="{{ route('questions.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
    </p>
    @endcan

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($questions) > 0 ? 'datatable' : '' }} @can('question_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('question_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.questions.fields.test')</th>
                        <th>@lang('quickadmin.questions.fields.question')</th>
                        <th>Pikët</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($questions) > 0)
                        @foreach ($questions as $question)
                            <tr data-entry-id="{{ $question->id }}">
                                @can('question_delete')
                                    <td></td>
                                @endcan

                                <td>{{ $question->test->name or '' }}</td>
                                <td>{{ $question->question }}</td>
                                <td>{{ $question->points }}</td>
                                <td>
                                    @can('question_view')
                                    <a href="{{ route('questions.show',[$question->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('question_edit')
                                    <a href="{{ route('questions.edit',[$question->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('question_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['questions.destroy', $question->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('question_delete')
            window.route_mass_crud_entries_destroy = '{{ route('questions.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questions.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.questions.fields.test')</th>
                            <td>{{ $question->test->name or '' }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.questions.fields.question')</th>
                            <td>{{ $question->question }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#answers" aria-controls="answers" role="tab" data-toggle="tab">Answers</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="answers">
<table class="table table-bordered table-striped {{ count($answers) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.answers.fields.question')</th>
                        <th>@lang('quickadmin.answers.fields.answer')</th>
                        <th>@lang('quickadmin.answers.fields.correct-answer')</th>
                        <th>@lang('quickadmin.answers.fields.points')</th>
                        <th>&nbsp;</th>
        </tr>
    </thead>

    <tbody>
        @if (count($answers) > 0)
            @foreach ($answers as $answer)
                <tr data-entry-id="{{ $answer->id }}">
                    <td>{{ $answer->question->question or '' }}</td>
                                <td>{{ $answer->answer }}</td>
                                <td>{{ Form::checkbox("correct_answer", 1, $answer->correct_answer == 1, ["disabled"]) }}</td>
                                <td>{{ $answer->points }}</td>
                                <td>
                                    @can('answer_view')
                                    <a href="{{ route('answers.show',[$answer->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('answer_edit')
                                    <a href="{{ route('answers.edit',[$answer->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('answer_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['answers.destroy', $answer->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="8">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('questions.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop